### ISSUE TITLE
Cake years are only available up to year 330

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyApi#126] opened 2024-04-22 17:27 UTC
![grafik](https://github.com/Coflnet/SkyApi/assets/58751503/1840025e-ceb6-4382-a2cc-a1b42723d364)

**Comment by Ekwav** [comment] 2024-04-22 20:25
Can't reproduce https://sky.coflnet.com/api/filter/options returns
```json
  {
    "name": "CakeYear",
    "options": [
      "0",
      "252"
    ],
    "type": 48,
    "longType": "NUMERICAL, RANGE",
    "description": "Supports number ranges, 0 for not present"
  }
```

**Comment by Ekwav** [comment] 2024-04-24 20:47
fixed with https://github.com/Coflnet/SkyFilter/commit/5ab97e94df78deaece7da6158ee2dd54b5e50dad

**Closed by Ekwav** 2024-04-24 20:47 UTC
Labels: bug
